asyncapi: 2.0.0
info:
  title: Streetlights API
  version: 1.0.0
  description: G2 RabbitMQ routing keys
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
defaultContentType: application/json
channels:
  msAuthConnectionDeleted:
    description: When a connection is deleted
    parameters:
      updatedId:
        $ref: '#/components/parameters/updatedId'
    publish:
      operationId: msAuthConnectionDeletedPublish
      message:
        contentType: application/json
        payload:
          $ref: '#/components/schemas/ms_auth-cache-connection'
    subscribe:
      operationId: msAuthConnectionDeletedSubscribe
      message:
        contentType: application/json
        payload:
          $ref: '#/components/schemas/ms_auth-cache-connection'
  msAuthConnectionUpdated:
    description: When a connection is updated
    parameters:
      updatedId:
        $ref: '#/components/parameters/updatedId'
    publish:
      operationId: msAuthConnectionUpdatedPublish
      message:
        contentType: application/json
        payload:
          $ref: '#/components/schemas/ms_auth-cache-connection'
    subscribe:
      operationId: msAuthConnectionUpdatedSubscribe
      message:
        contentType: application/json
        payload:
          $ref: '#/components/schemas/ms_auth-cache-connection'
components:
  parameters:
    updatedId:
      description: ID String
      schema:
        type: string
  schemas:
    ms_auth-cache-connection:
      type: object
      properties:
        username:
          type: string
        connections:
          type: array
          items:
            type: object
            properties:
              updated:
                type: string
                format: date
              state:
                type: string
              username:
                type: string
